---
- name: Installs Nginx with the latest version.
  apt: name=nginx-full state=latest
  
- name: Deploy virtual host config to sites enabled
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-enabled/{{ item.key }}
  with_dict: "{{ sites }}"
  
- name: Pull site from git
  git:
    repo={{ sites.value.repo }}
    dest=/usr/share/nginx/{{ item.key }}
  with_dict: "{{ sites }}"